name: snapqt5
summary: App to test snapcraft with recent versions of QT
description: It simply build a dummy app with some commands using the latest Qt libraries
confinement: strict
base: core18
grade: stable
version: 1.0.0

architectures:
  - build-on: amd64

plugs: # plugs for theming, font settings, cursor and to use gtk3 file chooser
  gtk-3-themes:
    interface: content
    target: $SNAP/data-dir/themes
    default-provider: gtk-common-themes:gtk-3-themes
  icon-themes:
    interface: content
    target: $SNAP/data-dir/icons
    default-provider: gtk-common-themes:icon-themes
  sound-themes:
    interface: content
    target: $SNAP/data-dir/sounds
    default-provider: gtk-common-themes:sounds-themes

apps:
  snapqt5:
    adapter: full
    #command: bin/snapcraft-preload $SNAP/opt/qt514/bin/snapqt5
    command: $SNAP/usr/bin/snapqt5
    command-chain: 
      - bin/desktop-launch
    desktop: usr/share/application/snapqt5.desktop
    environment:
      LD_LIBRARY_PATH: $SNAP/opt/qt514/lib/x86_64-linux-gnu/:$SNAP/opt/qt514/lib/:$LD_LIBRARY_PATH:$SNAP/usr/lib/
      QT_QPA_PLATFORM: xcb
      QT_BASE_DIR: $SNAP/opt/qt514/
      QT_PLUGIN_PATH: $SNAP/opt/qt514/plugins/
      QML2_IMPORT_PATH: $SNAP/opt/qt514/qml/
      XDG_DATA_DIRS: $SNAP/usr/share:$XDG_DATA_DIRS
      QT_QPA_PLATFORMTHEME: gtk3
    plugs: # https://snapcraft.io/docs/supported-interfaces
#input - output
      - x11 #monitor mouse/keyboard input
      - unity7 #access legacy desktop resources 
      - wayland #access compositors providing the Wayland protocol
      - desktop #provides access to common desktop elements
      - desktop-legacy #enables the use of legacy desktop methods
#access to hardware
      - opengl #access OpenGL hardware
      - optical-drive #read/write access to CD/DVD drives
      - removable-media #read/write files on removable storage devices
#networking
      - network #enables network access
      - network-bind #operate as a network service
#settings and files
      - cups-control #print documents
      - gsettings #access to any GSettings item for current user
      - home #access non-hidden files in the home directory
      - cifs-mount #access to smb and nfs file system
    #extensions: [gnome-3-28]

parts:
  desktop-qt5:
    source: https://github.com/ubuntu/snapcraft-desktop-helpers.git
    source-subdir: qt
    plugin: make
    make-parameters: ["FLAVOR=qt5"]
    build-packages:
      - build-essential
      - qtbase5-dev
      - dpkg-dev
    stage-packages:
      - libxkbcommon0
      - ttf-ubuntu-font-family
      - dmz-cursor-theme
      - light-themes
      - adwaita-icon-theme
      - gnome-themes-standard
      - shared-mime-info
      - libqt5gui5
      - libgdk-pixbuf2.0-0
      - libqt5svg5 # for loading icon themes which are svg
      - try: [appmenu-qt5] # not available on core18
      - locales-all
      - xdg-user-dirs
      - fcitx-frontend-qt5
      
  snapqt5:
    after: 
      - desktop-qt5
    source: https://github.com/jdelromano/snapqt5.git
    plugin: qmake
    project-files: 
      - src/snapqt5.pro
    qt-version: qt5
    build-packages:
      - build-essential
      - qtbase5-dev
      - libqt5core5a
      - libqt5gui5
      - libqt5widgets5
    override-build: |
      snapcraftctl build
      mkdir -p ${SNAPCRAFT_PART_INSTALL}/usr/bin
      mkdir -p ${SNAPCRAFT_PART_INSTALL}/usr/share/application
      cp src/snapqt5.desktop ${SNAPCRAFT_PART_INSTALL}/usr/share/application
      cp ${SNAPCRAFT_PART_BUILD}/snapqt5 ${SNAPCRAFT_PART_INSTALL}/usr/bin
      chmod +x ${SNAPCRAFT_PART_INSTALL}/usr/bin/snapqt5